add api numverify
apawlik96/formGenerator pull request #4
Opened 2024-01-08 17:16 UTC by apawlik96

2024-01-08 19:18 UTC, Y0ucandev requested changes

2024-01-08 19:18 UTC, Y0ucandev commented on src/form-element-creator.ts
> +    createPhoneInput = async (form: HTMLFormElement, element: any) => {
czy da sie nie uzywac any? tylko napisac jakis twardy typ w tym miejscu ?

2024-01-08 19:18 UTC, Y0ucandev commented on src/form-element-creator.ts
> +    private async countryApi(): Promise<Map<string, string>> {
wymysl lepsza nazwe dla tej funkcji. Bo ona nic mi nie mowi. Jest to rzeczownik a pamietaj ze nazwa funkcji to powinno byc wyrazenie rzeczownikowe lub czasownik

2024-01-08 19:18 UTC, Y0ucandev commented on src/form-generator-multi-step.ts
> +                    formElementCreator.createFormElement(form, element);
czym jest funkcja createForm element ? 
Co ona tworzy? jaki element? Bo brzmi ogolnie jakby miala tworzyc kazdy mozliwy a jednak telefonu nie potrafi zrobic :D bo masz do niej oddzielna funkcje. 
Poczytaj o strategii : 
https://refactoring.guru/design-patterns/strategy
I ogolnie o wzorcach projektowych. Zweryfikuj czy moze strategia miala by tu zastosowanie i sprobuj to zaimplementowac. 
Jezeli sie nie uda to bedziemy rozmawiac  o wzorcach projektowych na zajeciach :)

2024-01-08 19:18 UTC, Y0ucandev commented on src/form-generator-multi-step.ts
>  });
brak pustej linii na koncu pliku

2024-01-08 19:18 UTC, Y0ucandev commented on src/form-generator-one-step.ts
> +
mam wrazenei ze ten kawalek kodu juz gdzies sie powtarzal a skoro tak jest to moze warto zrobic z tego funkcje w jakiejs klasie typu form-utils.ts 
No i warto zaaplikowac moje uwagi z poprzedniego miejsca do tego rowniez. Niezaleznie czy strategia sie do tego nada czy nie

2024-01-08 19:18 UTC, Y0ucandev commented on src/form-generator-one-step.ts
>  });
dodaj pusta linie na koncu pliku

2024-01-08 19:18 UTC, Y0ucandev commented on src/validator.ts
>  }
dodaj pusta linie na koncu pliku. 
Wszedzie gdzie widzisz taki symbol to znaczy ze brakuje entera na samym koncu pliku. Z jakiegos powodu Git to weryfikuje i potem ma problem z tym :D 
<img width="281" alt="image" src="https://github.com/apawlik96/formGenerator/assets/112213953/e311932c-8607-457d-bb3e-bfbff05e2c35">

2024-01-15 19:39 UTC, Y0ucandev requested changes

2024-01-15 19:39 UTC, Y0ucandev commented on src/field-element-creation-strategy.ts
> +        const apiUrl = `http://apilayer.net/api/countries?access_key=c90144e214d92738b0be5d6e0652e1e4&number=14158586273`;
to powinno byc trzymane w stalej gdzies w oddzielnym pliku calkiem.
poczytaj o dobrych i zlych praktykach w trzymaniu wrazliwych danych
https://blog.logrocket.com/best-practices-for-managing-and-storing-secrets-in-frontend-development/

2024-01-15 19:39 UTC, Y0ucandev commented on src/field-element-creation-strategy.ts
> +        const response = await data.json();
na pewno potrzebujesz tutaj kolejnego awaita?

2024-01-15 19:39 UTC, Y0ucandev commented on src/form-element-creator.ts
> +export interface FormElementCreationStrategy {
kazda taka rzeczz to ma byc oddzielny plik

2024-01-15 19:39 UTC, Y0ucandev commented on src/form-element-creator.ts
> +    private selectElementCreationStrategy: SelectElementCreationStrategy;
nie widze sensu tutaj. Robisz strategie i tu uzywasz konkretnych implementacji strategii jako memberow klasy. Nie czuje tego. Trzeba to przemyslec bo strategia jest od tego zeby w memberach uzywac po prostu instancji strategii a tu uzywasz konkretnej implementacji.
Predzej powinno byc private selectCreation: ElementCreationStrategy - czy tam jak kolwiek sie ta Twoja strategia nazywa

2024-01-15 19:39 UTC, Y0ucandev commented on src/form-element-creator.ts
> +                console.log('Field type not recognized', element.class);
pytanie czy to powinien byc log czy error

2024-01-15 19:39 UTC, Y0ucandev commented on src/form-generator-multi-step.ts
> +    private creationStrategy: FormElementCreationStrategy;
tu jest dobre uzycie strategii

2024-01-18 14:06 UTC, Y0ucandev requested changes

2024-01-18 14:06 UTC, Y0ucandev commented on src/element-creator.ts
> +        // const element = document.createElement(tagName);
komentarz do usuniecia

2024-01-18 14:06 UTC, Y0ucandev commented on src/element-creator.ts
> +        if (typeof document !== 'undefined') {
w jakich przypadkach to byl undefined? ze musialas takiego ifa napisac

2024-01-18 14:06 UTC, Y0ucandev commented on src/field-element-creation-strategy.ts
> +                });
ten kawalek to bym wydzielil do innej metody, nie ma potrzeby rozwlekac tej metody na tak wiele linii a ten kawalek moze byc oddzielna metoda, po prostu zawolasz metode getCountryTelMap i tyle

2024-01-18 14:06 UTC, Y0ucandev commented on src/field-element-creation-strategy.ts
> +        const apiUrl = `http://apilayer.net/api/countries?apiKey=${apiKey}`;
to nalezy do pliku ENV wrzucic jakiegos tak jak chyba pisalem w ktoryms komentarzu

2024-01-18 14:06 UTC, Y0ucandev commented on src/form-element-creation-strategy-interface.ts
> +}
brak pustej linii na koncu pliku

2024-01-18 14:06 UTC, Y0ucandev commented on src/form-generator-multi-step.ts
> +        if (typeof document !== 'undefined') {
pytanie jw. kiedy tu byl undefined ? ze ten if zaczal byc potrzebny

2024-01-18 14:06 UTC, Y0ucandev commented on src/form-generator-multi-step.ts
> +    if (form) {
czyli co ? jak forma nie ma to nie robimy nic ? :D pytanie kiedy go nie bedzie faktycznie ze ten if jest potrzebny

2024-01-18 14:06 UTC, Y0ucandev commented on src/form-generator-one-step.ts
> +    if (form) {
jw

2024-01-18 14:06 UTC, Y0ucandev commented on src/form-generator-one-step.ts
> +        if (typeof document !== 'undefined' && document.body) {
jw

2024-01-18 14:06 UTC, Y0ucandev commented on src/form-styles.ts
> +        if (typeof document !== 'undefined') {
jw

2024-01-18 14:06 UTC, Y0ucandev commented on src/input-creation-strategy.js
> +        if (input) {
jw.

2024-01-22 13:19 UTC, apawlik96 commented on src/field-element-creation-strategy.ts
> +        const response = await data.json();
tak

2024-01-22 14:43 UTC, Y0ucandev requested changes

2024-01-22 14:43 UTC, Y0ucandev commented on src/field-element-creation-strategy.ts
> +        const paragraph = this.elementCreator.createElement('div');
wydzielic trzeba do stalych te powtarzajace sie stringi typu 'div', 'input'. 
najlepiej w oddzielnym pliku

2024-01-22 14:43 UTC, Y0ucandev commented on src/form-generator-multi-step.ts
>          const stepIndicatorContainer = document.createElement('div');
to tez stala wiec do pliku trzeba wydzielic

2024-01-22 14:43 UTC, Y0ucandev commented on src/form-generator-multi-step.ts
>          stepIndicatorContainer.className = 'step-indicator-container';
wszystkie stale trzeba tak wydzielic

2024-01-22 14:43 UTC, Y0ucandev commented on src/form-generator-multi-step.ts
> +    if (form) {
@apawlik96 follow up do tego :D bo nie wiem w sumie co z tym ma byc

2024-01-22 14:54 UTC, Y0ucandev commented on src/form-generator-multi-step.ts
> +    if (form) {
warto zrobic jakies logowanie jak nie wejdzie w tego ifa zeby wiedziec co sie dzieje

2024-01-30 11:02 UTC, Y0ucandev requested changes

2024-01-30 11:02 UTC, Y0ucandev commented on src/form-generator-multi-step.ts
>          stepIndicatorContainer.className = 'step-indicator-container';
nie widze wydzielenia do stalej tego.

2024-01-30 11:02 UTC, Y0ucandev commented on src/form-generator-multi-step.ts
> +        }
Fajnie by bylo zeby te napisy typu Next Previous Submit nie byly z palca wpisane. Zobacz Next powtarza sie dwa razy. Mowilem ostatnio o tym.
Poza tym dobrze by bylo zrobic jezyki. Np jak ktos chce miec strone po polsku to obecnie nie ma mozliwosci zeby mial polskie napisy. Zawsze beda angielskie. Fajnie dac wybor userowi. Wiec zrob pliki z tlumaczeniami. Poczekam na Twoj pomysl na zajeciach

2024-01-30 11:02 UTC, Y0ucandev commented on src/form-generator-multi-step.ts
> +        } else if (this.currentPageIndex == formPages.length - 1 && this.validateCurrentPage()) {
tu tez powtarza sie dwukrotnie obliczanie indexu

2024-01-30 11:02 UTC, Y0ucandev commented on src/validator.ts
> +        const phoneRegex = /^[\d\s-]+$/;
czy ten regex obsluguje wszystkie mozliwe numery telefonow z prefixami wlacznie ? :D

2024-02-07 14:16 UTC, Y0ucandev approved these changes

2024-02-07 14:17 UTC, merged